const numero1=9;
const numero2=3;
const resultadoSuma= numero1+numero2;
console.log (resultadoSuma);
const resultadoResta= numero1-numero2;
console.log (resultadoResta);
const resultadoMultiplicacion= numero1*numero2;
console.log (resultadoMultiplicacion);
const resultadoDivision= numero1/numero2;
console.log (resultadoDivision);